env:
    browser: true
    node: true
    es6: true
globals:
    globalThis: writable
    Atomics: readonly
    SharedArrayBuffer: readonly
extends:
    - 'plugin:react/recommended'
    - 'plugin:@typescript-eslint/recommended'
    - standard
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaFeatures:
        jsx: true
    ecmaVersion: 2018
    sourceType: module
    project: './tsconfig.json'
plugins:
    - react
    - react-hooks
    - '@typescript-eslint'
settings:
    react:
        version: 'detect'
rules:
    'semi': 'off'
    'comma-dangle': 'off'
    'no-void': 'off'
    'no-labels': 'off'
    'no-unused-vars': 'off'
    'no-lone-blocks': 'off'
    'react/prop-types': 'off'
    'sort-imports': 'off'
    'no-redeclare': 'off'
    'react/display-name': 'off'
    'react-hooks/rules-of-hooks': 'error'
    'react-hooks/exhaustive-deps': 'warn'
    'space-before-function-paren': 'off'
    'no-extra-parens': 'off'
    'no-control-regex': 'off'
    'prefer-const': 'off'
    'indent': 'off'
    'default-param-last': 'off'
    'no-use-before-define': 'off'
    '@typescript-eslint/no-unused-vars': 'warn'
    '@typescript-eslint/indent': ['off', 4]
    '@typescript-eslint/no-var-requires': 'off'
    '@typescript-eslint/no-use-before-define': ['error']
    '@typescript-eslint/explicit-module-boundary-types': 'off'
    '@typescript-eslint/explicit-function-return-type': 'off'
    # '@typescript-eslint/member-delimiter-style': ['warn', { multiline: { delimiter: 'none' }, singleline: { delimiter: 'comma' } }]
    '@typescript-eslint/no-explicit-any': 'off'
    'node/no-callback-literal': 'off'
